# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseExample
  pod 'Firebase/Auth'
  pod 'FirebaseUI', '~> 8.0'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

end
